inherit_mode:
  merge:
    - Exclude
    - Include

inherit_from:
  - ./lib/rubocop/cop/local/default.yml

require:
  - ./lib/rubocop/cop/local/rules.rb

plugins:
  - rubocop-erb
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions:
    rubocop-factory_bot: false
  Exclude:
    - 'lib/dtext_rb/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - class_methods
    - class_eval
    - included
    - concerning
    - context
    - create_table
    - factory
    - FactoryBot.define
    - should
    - should_eventually
    - scoped
  Exclude:
    - config/routes.rb
    - config/environments/*.rb
    - db/seeds.rb
    - db/seeds/*.rb
    - db/migrate/*.rb

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpStatus:
  EnforcedStyle: symbolic

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb
    - db/seeds/*.rb
    - db/fixes/*.rb
  Include:
    - test/**/*.rb

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/WhereEquals:
  Enabled: false

Rails/WhereExists:
  EnforcedStyle: exists

Rails/WhereNotWithMultipleConditions:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FloatDivision:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MapIntoArray:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PerlBackrefs:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/NotNullColumn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Rails/DynamicFindBy:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - lib/generators/**/*.rb

Rails/TimeZoneAssignment:
  Enabled: true
  Exclude:
    - test/**/*.rb

Lint/UriEscapeUnescape:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Security/Open:
  Enabled: true
  Exclude:
    - app/logical/storage_manager/ftp.rb

Naming/MethodParameterName:
  Enabled: true
  # Adding overrides the defaults: https://docs.rubocop.org/rubocop/cops_naming.html#configurable-attributes-namingmethodparametername
  AllowedNames:
    - a
    - b
    - q
    - o
    - as
    - at
    - by
    - cc
    - db
    - id
    - if
    - in
    - io
    - ip
    - of
    - on
    - os
    - pp
    - to

Local/CurrentUserOutsideOfRequests:
  Enabled: true
  Exclude:
    - db/fixes/1*.rb
    - db/fixes/204*.rb
    - db/fixes/205*.rb
    - config/environments/development.rb
    - app/logical/session_loader.rb
    - test/unit/current_user_test.rb

Rails/SquishedSQLHeredocs:
  Enabled: true
  Exclude:
    - db/migrate/*.rb
